import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Testing Nextjs',
  description: 'Generated by create next app',
 openGraph: {
    title: "Experice Beyond Ownership",
    description: "The IP perks.",
  },
}

export default function RootLayout({
  children,
  auth
}: {
    children: React.ReactNode
    auth: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}
        {auth}
      </body>
    </html>
  )
}
